Linuxawy diaries 2
librebooks/website pull request #19
Opened 2024-02-21 07:13 UTC by Tasneem-Abouzaid

اضافة كتاب يوميات لينكساوي – الجزء الثاني.

2024-02-22 21:56 UTC, aabouzaid requested changes
@Tasneem-Abouzaid 
يوجد كتاب مضاف بالخطأ.

2024-02-24 23:10 UTC, aabouzaid commented on content/books/linuxawy-diaries-2/linuxawy-diaries-2.md
> +---
@Tasneem-Abouzaid 
أبعاد الغلاف غير صحيحة.

2024-02-28 12:03 UTC, Tasneem-Abouzaid commented on content/books/linuxawy-diaries-2/linuxawy-diaries-2.md
> +---
تعديل واضافة  كتاب يوميات لينكساوي – الجزء الثاني.

2024-02-28 17:02 UTC, aabouzaid approved these changes

2024-02-28 17:02 UTC, merged