added: book search-engine-optimization-seo-starter-guide-ar
librebooks/website pull request #23
Opened 2024-02-21 12:41 UTC by Tasneem-Abouzaid

اضافة كتاب تحسين محركات البحث SEO – دليل المبتدئين.

2024-02-22 21:59 UTC, aabouzaid requested changes
@Tasneem-Abouzaid 
لا يوجد غلاف.

2024-02-24 23:13 UTC, aabouzaid commented on content/books/search-engine-optimization-seo-starter-guide-ar/search-engine-optimization-seo-starter-guide-ar.md
> +---
@Tasneem-Abouzaid 
الغلاف غير موجود.

2024-02-24 23:13 UTC, aabouzaid commented on content/books/search-engine-optimization-seo-starter-guide-ar/search-engine-optimization-seo-starter-guide-ar.md
> +SEO -
@Tasneem-Abouzaid 
السطر مكتوب بشكل خاطئ. يجب أن يبدأ بعلامة "-".

2024-02-28 11:32 UTC, Tasneem-Abouzaid commented
اضافة غلاف كتاب تحسين محركات البحث SEO – دليل المبتدئين.

2024-02-28 17:03 UTC, aabouzaid approved these changes

2024-02-28 17:03 UTC, merged