added: book debian-handbook-arabic
librebooks/website pull request #29
Opened 2024-02-22 09:31 UTC by Tasneem-Abouzaid

اضافة كتاب دفتر مدير دبيان.

2024-02-22 21:45 UTC, aabouzaid requested changes
@Tasneem-Abouzaid 
الصورة بجودة منخفضة.

2024-02-28 12:26 UTC, Tasneem-Abouzaid commented
تعديل غلاف كتاب دفتر مدير دبيان.

2024-02-28 17:03 UTC, aabouzaid commented
@Tasneem-Abouzaid 
> تعديل غلاف كتاب دفتر مدير دبيان.

أبعاد الغلاف غير صحيحة (يجب أن يكون أصغر).

2024-02-28 18:21 UTC, aabouzaid approved these changes

2024-02-28 18:21 UTC, merged